# Generated by Django 4.1.1 on 2022-09-13 14:33

from django.db import migrations
import json

from django.contrib.gis.geos import fromstr
from pathlib import Path

DATA_FILENAME = "baltimore_query.json"


def load_data(apps, schema_editor):
    Shop = apps.get_model("nearbyshops", "Shop")
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as data_file:
        objects = json.load(data_file)
        for obj in objects["elements"]:
            try:
                obj_type = obj["type"]
                if obj_type == "node":
                    tags = obj["tags"]
                    name = tags.get("name", "no-name")
                    longitude = obj.get("lon", 0)
                    latitude = obj.get("lat", 0)
                    location = fromstr(f"Point({longitude} {latitude})", srid=4326)
                    Shop(name=name, location=location).save()
            except KeyError:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("nearbyshops", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_data)]
